name: Publish to npm

on:
  push:
    tags:
      - 'v*' # Runs on tags like v1.0.0

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    environment: NPM_TOKEN

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version from tag, commit and push
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          VERSION="${TAG_NAME#v}"
          echo "Tag: $TAG_NAME, Version: $VERSION"
          npm version --no-git-tag-version "$VERSION"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "chore: update version to $VERSION from tag"
          # Only push commit, do not push tag (avoid tag conflict)
          git push origin HEAD:refs/heads/${GITHUB_HEAD_REF:-$(echo $GITHUB_REF | sed 's/refs\/tags\///')}
        env:
          GITHUB_REF: ${{ github.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # or match your project's version
          registry-url: 'https://registry.npmjs.org'

      - run: |
          npm whoami
          echo "🧙‍♂️ Authenticating as the package overlord..."
          echo "🚀 Initiating launch sequence for your legendary code."
          echo "📦 Publishing your masterpiece to the npm galaxy..."
          echo "🔥 Stand back, world. Innovation is deploying..."
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        run: npm publish --access public || echo "Publish failed but continuing workflow"
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
